### ISSUE TITLE
i can not found utilities

### ISSUE THREAD

**Issue by xin7c** [appium/appium-for-mac#107]
import utilities

it s not work!

so where is the utilities lib???

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium/appium-for-mac/blob/b5c9ca882c10ff7668f7c1208a81bcb052aade34/examples/SeleniumConf%20April%202017/utilities.py ?
Then, you should run the command in `examples/SeleniumConf April 2017` with Python 2.
It does not work with python 3
