### ISSUE TITLE
screenshot for app main window only

### ISSUE THREAD

**Issue by fangmobile** [appium/appium-for-mac#12]
I am working on a project that use Appium-for-mac for automation as well as screenshot comparison against base images (using a tool called Applitools Eyes). Current screenshot implementation makes this impossible because it takes the whole screen. Any machine change or background windows change will fail the image comparison test.
Without making my app full screen or apple Scriptable, I tried a different implementation that will take screenshot of the app windows only, using CGWindow API. This is a caveat, I also lose the ability to take screenshot of the menu.
Would you be willing to take a look?
https://github.com/fangmobile/appium-for-mac/tree/appOnlyScreenshot
Any feedback and suggestions?

**Comment by ERPChina** [comment]
in which release I can get the fix, I am using beta3 release of AppumForMac, but still get the screenshot of full screen. Thanks!
