### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by thecodesmith** [appium/appium-for-mac#16]
What is the status of this project? I'm looking to automate a Mac GUI using this same model (WebDriver, JWP), and curious if this project might meet our needs, or get us partway there.

- Is it largely functional?
- Known limitations?

Thanks for your work on this!

**Comment by jlipps** [comment]
I sincerely doubt that it is functional anymore. It was kind of too slow to be practical in the past. We may look at it again in the future though. It'd be great to re-implement this as an Appium driver in the new style, maybe leveraging XCUITest if it supports native apps too?
