### ISSUE TITLE
Unable to "Quit" from an application 

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [appium/appium-for-mac#37]
Hi!
I am working on tests for macOS applications. I tried to close application via "Close" button but in some cases I should use "Quit" (`Command + Q`) to close the application completely. I found that I can't use `Command` button because of it throws an exception:
```
System.ArgumentException : key must be a modifier key (Keys.Shift, Keys.Control, or Keys.Alt)
Parameter name: key
```
I use next line of code: 
```
new Actions(this.driver).KeyUp(Keys.Command).SendKeys("Q").Perform();
``` 

How can I quit from the application (close it completely)  and why I can't use `Command` button?

**Comment by stuartbrussell-intuit** [comment]
I'm not sure why Command isn't recognized in your case. The following is what I use (python). You do need to press command before typing 'q', and then release command afterwards. Note that 'q' is lower case. hth!

from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
....
ActionChains(driver).key_down(Keys.COMMAND).send_keys('q').key_up(Keys.COMMAND).perform()

**Comment by mykyta-bondarenko-gl** [comment]
Thanks @stuartbrussell-intuit, you are right, it works using python. So it's C# wrapper issue.
Sorry for that.

**Comment by stuartbrussell-intuit** [comment]
Closing issue.
