### ISSUE TITLE
Does Appium for Mac support third party applications like "skype" and others or just supports only apple's native desktop applications like facetime and calculator for desktop automation 

### ISSUE THREAD

**Issue by SohilKumar** [appium/appium-for-mac#41]
Hello everyone ,
 i'm trying to automate one of our companies desktop application

Initially i have gone through the steps from this link :  https://github.com/appium/appium-for-mac 
and i was able to successfully automate Apple Face-time desktop application through appium-for-mac
i had the identifiers and xpaths so it was fine, but the problem is when ever i try to build the xpath or find the elements name for the third party desktop apps for example (skype) it does not generate the xpath at all a simple example : 

Facetime end call button xpath : "/AXApplication[@AXTitle='FaceTime']/AXWindow[@AXTitle='FaceTime' and @AXSubrole='AXStandardWindow']/AXButton[@AXTitle='End']";

But for my application if i try to identify any elements and try build the xpath it like this:
"/AXTextField[@AXSubrole='AXUnknown']"

what is the difference my question is  : 
-> do we need to sign the application like same we do for mobile apps
-> or there is any documentation or any link how to automate third party desktop apps other than apple native apps @mykola-mokhnach @jlipps @penguinho @imurchie

**Comment by akamat4477** [comment]
We should be able to automate any mac os desktop application.
It's working fine for my desktop application 
Better to use absolute xpath 
Ex:"/AXApplication[@AXTitle='Enrollment']/AXWindow[@AXTitle='Native Enrollment']/AXTextField[@AXPlaceholderValue='Username']"

**Comment by tiecongli** [comment]
I have the same question. I seems some of the 3p app work (some Chinese dictionary app) but some don't (e.g. slack).

**Comment by jlipps** [comment]
As far as I know, this only supports apps that are developed using the standard mac OS UI APIs. So hybrid apps (Slack) or Qt apps probably won't work.
