### ISSUE TITLE
Appium for Mac is not working with latest version of Mac OS

### ISSUE THREAD

**Issue by moatazeldebsy** [appium/appium-for-mac#49]
Appium for Mac is not working with latest version of Mac OS 
<img width="599" alt="screenshot 2019-01-16 at 17 19 59" src="https://user-images.githubusercontent.com/45570191/51262933-9d469600-19b3-11e9-980c-c1b67207ed69.png">

**Comment by Jonahss** [comment]
Ah, did you solve your issue? You will need to change your security settings to allow apps from unidentified developers.

https://kb.wisc.edu/page.php?id=25443
