### ISSUE TITLE
AppiumDriver.quit() not closing the app

### ISSUE THREAD

**Issue by moatazeldebsy** [appium/appium-for-mac#50]
When trying to close the app using the driver command `driver.quit()` or `driver. close()` , the app is still opened

**Comment by Jonahss** [comment]
Ah thank you for reporting.

If you want a workaround, it'd be to click the close button in the upper left corner or the window, but I agree that this should be a working feature.

**Comment by smrutivn** [comment]
We are facing the same issue. Is there a fix for this issue?
