### ISSUE TITLE
Screenshots for appium for mac

### ISSUE THREAD

**Issue by kimjunte** [appium/appium-for-mac#52]
The image file is not readable within Ubuntu 18.04 when you save the screen shot to a file. Seems like a faulty png

**Comment by kimjunte** [comment]
![32](https://user-images.githubusercontent.com/39764191/51913067-9f561f00-23cd-11e9-8383-b414aa7a2f17.png)

**Comment by kimjunte** [comment]
I have attached one of the 'screenshots' it does for mac.

**Comment by michaelelcat** [comment]
Having a very similar issue. Any update on this?

**Comment by Jiurong-Yang** [comment]
You can open it with gimp. But maybe not other image viewer software. I think it has to do with weird color schema used by Mac OS

**Comment by KazuCocoa** [comment]
This screenshot is by below native screenshot command by macOS. Potentially, their PNG format is wrong or need to use other image viewers. (Probably nothing we can do for now. Or re-write this logic with another way...?)
https://github.com/appium/appium-for-mac/blob/6a60be0bdc67a05146dc00696a4855ae7f966526/AppiumForMac/Server/Controller/AfMSessionController.m#L1832-L1846
