### ISSUE TITLE
64-bit version

### ISSUE THREAD

**Issue by dcolley** [appium/appium-for-mac#72]
When can we expect the 64-bit version?
I tried Appium on OSX 10.15 and I get the dreaded 32-bit incompatibility error

**Comment by dcolley** [comment]
I can confirm that this works for me (to start the AppiumForMac server):

```
git clone https://github.com/appium/appium-for-mac
```
Launch Xcode
Open AppiumForMac.xcodeproj
Click Run in the toolbar

I don't know enough about Xcode to build this for /Applications

**Comment by KazuCocoa** [comment]
ah...
VALID_ARCHS = x86_64; is in the project now.
So, maybe it depends on the building environment.
(as https://github.com/appium/appium-for-mac/issues/72#issuecomment-534623155 , it should work well)

**Comment by KazuCocoa** [comment]
Added build section to be able to build by manual for now. (and move to `/Applications`)
