### ISSUE TITLE
is it support for mac 10.15

### ISSUE THREAD

**Issue by StarSkyYe** [appium/appium-for-mac#75]
I just download the release AppiumForMac(beta 3)
and then open it.
it seems to be started, but nothing shows in the desktop.
PS: i am working with macOS 10.15

**Comment by KazuCocoa** [comment]
Any logs about it?

**Comment by StarSkyYe** [comment]
where is tool log?

**Comment by Carlbc18** [comment]
I have been able to get this to work on 10.13 - 10.15 recently

installed node, npm
npm installed appium
Download appium-mac, allow the app in system preferences accessibility, and allow any other app calling into it.

if you're running things out of terminal for example allow terminal.  If doing something over ssh allow the ssh-keygen-wrapper, for example.

**Comment by StarSkyYe** [comment]
ok, I will try for it. Thanks

**Comment by KazuCocoa** [comment]
I tried to run mac driver on the Catalina env. It worked.

I thought something crash happened.
