### ISSUE TITLE
WD Proxy unable to get Appium4Mac http server port

### ISSUE THREAD

**Issue by sankalpphirke** [appium/appium-for-mac#79]
I am trying to create parallel execution for macos application and thought of creating appium4mac instances on different port and run/switch between them as required.  But i am getting below issue

[Appium] Welcome to Appium v1.16.0-rc.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 11154
[Appium]   defaultCapabilities: {
[Appium]     app: Convo Dev
[Appium]     deviceName: Mac
[Appium]     newCommandTimeout: 300
[Appium]     noReset: false
[Appium]     platformName: Mac
[Appium]   }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: Convo Dev
[Appium]   deviceName: Mac
[Appium]   newCommandTimeout: 300
[Appium]   noReset: false
[Appium]   platformName: Mac
[Appium] Appium REST http interface listener started on 127.0.0.1:11154
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 73
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 73
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"Convo Dev","noReset":"false","platformName":"Mac","deviceName":"Mac","newCommandTimeout":300},"capabilities":{"firstMatch":[{"appium:app":"Convo Dev","appium:deviceName":"Mac","appium:newCommandTimeout":300,"appium:noReset":"false","platformName":"mac"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"Convo Dev","noReset":"false","platformName":"Mac","deviceName":"Mac","newCommandTimeout":300},null,{"firstMatch":[{"appium:app":"Convo Dev","appium:deviceName":"Mac","appium:newCommandTimeout":300,"appium:noReset":"false","platformName":"mac"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1577089419988 (13:53:39 GMT+0530 (India Standard Time))
[Appium] Appium v1.16.0-rc.1 creating new MacDriver (v1.7.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "mac",
[debug] [BaseDriver]     "appium:app": "Convo Dev",
[debug] [BaseDriver]     "appium:deviceName": "Mac",
[debug] [BaseDriver]     "appium:newCommandTimeout": 300,
[debug] [BaseDriver]     "appium:noReset": "false"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   app
[BaseDriver] Session created with session id: 9f33bd01-850d-4fe7-9e78-acae62153bc4
[MacDriver] Killing any old AppiumForMac
[MacDriver] Successfully cleaned up old Appium4Mac servers
[MacDriver] Spawning AppiumForMac with: undefined
[Appium4Mac] [STDERR] 2019-12-23 13:53:40:165 AppiumForMac[1768:307] HTTPServer: Started HTTP server on port 50369
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4622/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"mac","app":"Convo Dev","deviceName":"Mac","newCommandTimeout":300,"noReset":false}}
[WD Proxy] Got an unexpected response with status undefined: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":4622}
[debug] [MacDriver] Deleting AppiumForMac session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1577089420185 (13:53:40 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:4622
[debug] [W3C]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:270:13)
[HTTP] <-- POST /wd/hub/session 500 215 ms - 572
[HTTP] 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:4622
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INFPUMAC07.local', ip: '2401:4900:197f:410d:20da:227e:8ee3:2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:4622
    at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:270:13)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INFPUMAC07.local', ip: '2401:4900:197f:410d:20da:227e:8ee3:2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:105)
	at config.Utils.CD(Utils.java:172)
	at pages.MacOS_App_pageobjects.<init>(MacOS_App_pageobjects.java:19)
	at testcases.MacosApp.login_macos_app(MacosApp.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRun

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-mac-driver/blob/789b3678297ba64a53be89f98e2d9570016d0eaf/lib/appium-for-mac.js#L16-L17 should be configurable (not supported yet)

**Comment by sankalpphirke** [comment]
Thanks for the response. I tried configuring it with different ways but could not succeed , if you could help  me getting this done.

const DEFAULT_A4M_HOST = '127.0.0.1';
exports.DEFAULT_A4M_HOST = DEFAULT_A4M_HOST;
const DEFAULT_A4M_PORT =  await this.getPort();
exports.DEFAULT_A4M_PORT = DEFAULT_A4M_PORT;

const REQ_A4M_APP_PATH = _path.default.resolve('/Applications', 'AppiumForMac.app');

const a4mLog = _appiumSupport.logger.getLogger('Appium4Mac');

class AppiumForMac {
  constructor() {
    this.proxyHost = DEFAULT_A4M_HOST;
    this.proc = null; 
    this.proxyPort = DEFAULT_A4M_PORT;
    this.jwproxy = new _appiumBaseDriver.JWProxy({
      server: this.proxyHost,
      port: this.proxyPort
    });
  }

  async start() {
    if (!(await _appiumSupport.fs.exists(REQ_A4M_APP_PATH))) {
      throw new Error('Could not verify AppiumForMacDriver install; please install to your /Applications folder');
    }

    const startDetector = (stdout, stderr) => { 
      return stderr.indexOf('Started HTTP server') !== -1;
    };

    let processIsAlive = false;

    try {
      await this.killAll();
      const a4mBinary = _path.default.resolve(REQ_A4M_APP_PATH, 'Contents', 'MacOS', 'AppiumForMac');
      this.proc = new _teen_process.SubProcess(a4mBinary, []);
      processIsAlive = true;
      for (let stream of ['STDOUT', 'STDERR']) {
        this.proc.on(`lines-${stream.toLowerCase()}`, lines => {
          for (let l of lines) {
            a4mLog.info(`[${stream}] ${l.trim()}`);
          }
        });
      }
      this.proc.on('exit', (code, signal) => {
        processIsAlive = false;
        let msg = `AppiumForMac exited unexpectedly with code ${code}, ` + `signal ${signal}`;

        _logger.default.error(msg);
      });

      _logger.default.info(`Spawning AppiumForMac with: ${this.appium4macdriver}`);

      await this.proc.start(startDetector);
      await this.waitForOnline();
    } catch (e) {
      this.emit(AppiumForMac.EVENT_ERROR, e);

      if (processIsAlive) {
        await this.proc.stop();
      }

      _logger.default.errorAndThrow(e);
    }
  }

  sessionId() {
    if (this.state !== AppiumForMac.STATE_ONLINE) {
      return null;
    }
    _logger.default.debug('-------->'+this.jwproxy.sessionId);
    return this.jwproxy.sessionId;
  }

  async waitForOnline() {
    return true;
  }

  async getStatus() {
    return await this.sendCommand('/status', 'GET');
  }

  async startSession(caps) {
    this.proxyReqRes = this.jwproxy.proxyReqRes.bind(this.jwproxy);
    await this.sendCommand('/session', 'POST', {
      desiredCapabilities: caps
    });
  }
   async getPort()
  { 
    const { execSync } = require('child_process');
    const stdout = execSync('lsof -i -P -n | grep AppiumFor');
    var stdout1 = String(stdout);
    var patt1 = /\*:(.*?)\(/;
    var result = stdout1.match(patt1)[1];
    this.DEFAULT_A4M_PORT = result.trim();
    _logger.default.debug(result)
    return result;
  }

  async stop() {
    try {
      if (this.proc) {
        await this.proc.stop();
      }
    } catch (e) {
      _logger.default.error(e);
    }
  }

  async sendCommand(url, method, body) {
    let res;

    try {
      res = await this.jwproxy.command(url, method, body);
    } catch (e) {
      if (e.message.indexOf('Did not get a valid response object') === -1 || e.message.indexOf('value') !== -1) {
        throw e;
      }
    }

    return res;
  }

  async proxyReq(req, res) {
    return await this.jwproxy.proxyReqRes(req, res);
  }

  async killAll() {
    const processName = 'AppiumForMac';

    _logger.default.info(`Killing any old AppiumForMac`);

    await _appiumSupport.process.killProcess(processName);

    _logger.default.info('Successfully cleaned up old Appium4Mac servers');
  }

  async deleteSession() {
    _logger.default.debug('Deleting AppiumForMac server session');

    try {
      await this.sendCommand('/', 'DELETE');
    } catch (err) {
      _logger.default.warn(`Did not get confirmation AppiumForMac deleteSession worked; ` + `Error was: ${err}`);
    }
  }

}

exports.AppiumForMac = AppiumForMac;
var _default = AppiumForMac;
exports.default = _default;require('source-map-support').install();

**Comment by sankalpphirke** [comment]
Thanks for you response, I tried learning basics if JS to do it on my own , but could not succeed yet.
I tried doing something like this


const DEFAULT_A4M_HOST = '127.0.0.1';
exports.DEFAULT_A4M_HOST = DEFAULT_A4M_HOST;
const DEFAULT_A4M_PORT =  await this.getPort();
exports.DEFAULT_A4M_PORT = DEFAULT_A4M_PORT;

const REQ_A4M_APP_PATH = _path.default.resolve('/Applications', 'AppiumForMac.app');

const a4mLog = _appiumSupport.logger.getLogger('Appium4Mac');

class AppiumForMac {
  constructor() {
    this.proxyHost = DEFAULT_A4M_HOST;
    this.proc = null; 
    this.proxyPort = DEFAULT_A4M_PORT;
    this.jwproxy = new _appiumBaseDriver.JWProxy({
      server: this.proxyHost,
      port: this.proxyPort
    });
  }

  async start() {
    if (!(await _appiumSupport.fs.exists(REQ_A4M_APP_PATH))) {
      throw new Error('Could not verify AppiumForMacDriver install; please install to your /Applications folder');
    }

    const startDetector = (stdout, stderr) => { 
      return stderr.indexOf('Started HTTP server') !== -1;
    };

    let processIsAlive = false;

    try {
      await this.killAll();
      const a4mBinary = _path.default.resolve(REQ_A4M_APP_PATH, 'Contents', 'MacOS', 'AppiumForMac');
      this.proc = new _teen_process.SubProcess(a4mBinary, []);
      processIsAlive = true;
      for (let stream of ['STDOUT', 'STDERR']) {
        this.proc.on(`lines-${stream.toLowerCase()}`, lines => {
          for (let l of lines) {
            a4mLog.info(`[${stream}] ${l.trim()}`);
          }
        });
      }
      this.proc.on('exit', (code, signal) => {
        processIsAlive = false;
        let msg = `AppiumForMac exited unexpectedly with code ${code}, ` + `signal ${signal}`;

        _logger.default.error(msg);
      });

      _logger.default.info(`Spawning AppiumForMac with: ${this.appium4macdriver}`);

      await this.proc.start(startDetector);
      await this.waitForOnline();
    } catch (e) {
      this.emit(AppiumForMac.EVENT_ERROR, e);

      if (processIsAlive) {
        await this.proc.stop();
      }

      _logger.default.errorAndThrow(e);
    }
  }

  sessionId() {
    if (this.state !== AppiumForMac.STATE_ONLINE) {
      return null;
    }
    _logger.default.debug('-------->'+this.jwproxy.sessionId);
    return this.jwproxy.sessionId;
  }

  async waitForOnline() {
    return true;
  }

  async getStatus() {
    return await this.sendCommand('/status', 'GET');
  }

  async startSession(caps) {
    this.proxyReqRes = this.jwproxy.proxyReqRes.bind(this.jwproxy);
    await this.sendCommand('/session', 'POST', {
      desiredCapabilities: caps
    });
  }
   async getPort()
  { 
    const { execSync } = require('child_process');
    const stdout = execSync('lsof -i -P -n | grep AppiumFor');
    var stdout1 = String(stdout);
    var patt1 = /\*:(.*?)\(/;
    var result = stdout1.match(patt1)[1];
    this.DEFAULT_A4M_PORT = result.trim();
    _logger.default.debug(result)
    return result;
  }

  async stop() {
    try {
      if (this.proc) {
        await this.proc.stop();
      }
    } catch (e) {
      _logger.default.error(e);
    }
  }

  async sendCommand(url, method, body) {
    let res;

    try {
      res = await this.jwproxy.command(url, method, body);
    } catch (e) {
      if (e.message.indexOf('Did not get a valid response object') === -1 || e.message.indexOf('value') !== -1) {
        throw e;
      }
    }

    return res;
  }

  async proxyReq(req, res) {
    return await this.jwproxy.proxyReqRes(req, res);
  }

  async killAll() {
    const processName = 'AppiumForMac';

    _logger.default.info(`Killing any old AppiumForMac`);

    await _appiumSupport.process.killProcess(processName);

    _logger.default.info('Successfully cleaned up old Appium4Mac servers');
  }

  async deleteSession() {
    _logger.default.debug('Deleting AppiumForMac server session');

    try {
      await this.sendCommand('/', 'DELETE');
    } catch (err) {
      _logger.default.warn(`Did not get confirmation AppiumForMac deleteSession worked; ` + `Error was: ${err}`);
    }
  }

}

exports.AppiumForMac = AppiumForMac;
var _default = AppiumForMac;
exports.default = _default;require('source-map-support').install();

but this result in failure ,with other attempts to make it run in constructor where it assign previous running port. Would you please help me on this.

> Perhaps https://github.com/appium/appium-mac-driver/blob/789b3678297ba64a53be89f98e2d9570016d0eaf/lib/appium-for-mac.js#L16-L17 should be configurable (not supported yet)

**Comment by KazuCocoa** [comment]
Made the port configurable by appium-mac-driver.
The port should be managed by test script side via capabilities as Appium's design.
