### ISSUE TITLE
Get page source not returning element's coordinates

### ISSUE THREAD

**Issue by alexguimaraes** [appium/appium-for-mac#83]
Hi,

Since i'm able to get the elements coordinates/dimensions when using a locator strategy i was wondering why isn't that information provided on the getPageSource method.

I think this is more of a global issue but my i'm writting code in Java, using appium 1.17. and MacOS 10.14.6

Edit: I added the feature if you're interested 
https://github.com/appium/appium-for-mac/pull/84

Thank you in advance

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-for-mac/pull/84 has been merged
