### ISSUE TITLE
Unable to click or tap on images. perform() method not supported in appium for mac.

### ISSUE THREAD

**Issue by vijayqa** [appium/appium-for-mac#98]
Hi, We are trying to automate Mac standalone application developed in Xamarine platform, For check boxes and radio buttons they have used images. We are unable to perform tap option since .perform() method is not supported. getting unsupported command exception.
org.openqa.selenium.UnsupportedCommandException: 
For trying to click() on image, getting webDriver exception.
Below is the sample xpath.
driver.findElement(By.xpath("/AXApplication[@AXTitle='Plugged']/AXWindow[@AXTitle='E plugged' and @AXSubrole='AXStandardWindow']/AXImage[@AXIdentifier='chkBoxTermsAndCondition']")).click();

**Comment by vijayqa** [comment]
This worked for me, https://github.com/appium/appium-for-mac/issues/80

This root cause is this repository does not support /actions for send keys to the active elements command as W3C yet. Java client sends the /actions as the command instead of session/:session_id/keys. session/:session_id/keys is MJSONWP.

As a workaround in Java client, you can try forceMjsonwp as appium/java-client#969 (comment) . Then, Java client works as MJSONWP.

**Comment by KazuCocoa** [comment]
ah, okay. Thanks for leaving the solution
